### ISSUE TITLE
target_charについて

### ISSUE THREAD

**Issue by C0A21154** [c0a21038/ProjExD#6]
https://github.com/c0a21038/ProjExD/blob/044efa27ffa8b99c73a648387ea24314d9ef1a2e/ex01/alphabet.py#L19
rangeを65から91までにしてfor文を回せば、alpha_listが必要なくなるのでは？

**Comment by c0a21038** [comment]
ここのrangeは空のリストに10回文字を追加して対象文字のリストを作るためなので65から91にしてしまうと数が変わってくるためそこの変更はしませんでした。しかし、修正前では同じ文字がでてしまったため、popの位置を変えることで同じ文字が出ないようにしました。
